name: pacini_typing
channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - kma=1.4.15
  - pip=24.2
  - python=3.12.7
  - blast=2.16.0
  - pip:
      - pyyaml==6.0.2
      - setuptools==75.1.0
      - pytest==8.3.3
      - pandas===2.5.3