name: pacini-typing
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blast=2.16.0
  - bzip2=1.0.8
  - c-ares=1.34.3
  - ca-certificates=2024.8.30
  - curl=8.10.1
  - entrez-direct=22.4
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - keyutils=1.6.1
  - kma=1.4.15
  - krb5=1.21.3
  - ld_impl_linux-64=2.43
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libcurl=8.10.1
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgomp=14.2.0
  - libidn2=2.3.7
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libsqlite=3.47.0
  - libssh2=1.11.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncbi-vdb=3.1.1
  - ncurses=6.5
  - openssl=3.4.0
  - perl=5.32.1
  - perl-archive-tar=2.40
  - perl-carp=1.50
  - perl-common-sense=3.75
  - perl-compress-raw-bzip2=2.201
  - perl-compress-raw-zlib=2.202
  - perl-encode=3.21
  - perl-exporter=5.74
  - perl-exporter-tiny=1.002002
  - perl-extutils-makemaker=7.70
  - perl-io-compress=2.201
  - perl-io-zlib=1.14
  - perl-json=4.10
  - perl-json-xs=4.03
  - perl-list-moreutils=0.430
  - perl-list-moreutils-xs=0.430
  - perl-parent=0.242
  - perl-pathtools=3.75
  - perl-scalar-list-utils=1.68
  - perl-storable=3.15
  - perl-types-serialiser=1.01
  - pip=24.3.1
  - python=3.12.7
  - readline=8.2
  - rpsbproc=0.5.0
  - setuptools=75.5.0
  - tk=8.6.13
  - wget=1.21.4
  - wheel=0.45.0
  - xz=5.2.6
  - zlib=1.3.1
  - zstd=1.5.6
  - pip:
      - numpy==2.1.3
      - pandas==2.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pyyaml==6.0.2
      - six==1.16.0
      - tzdata==2024.2
      - cgecore==2.0.1
