name: pacini-typing
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bzip2=1.0.8
  - kma=1.4.15
  - pip=24.2
  - python=3.12.7
  - pip:
      - pyyaml==6.0.2
      - setuptools==75.1.0
      - pytest==8.3.3
      - pandas===2.2.3
  - c-ares=1.34.3
  - ca-certificates=2024.8.30
  - curl=8.10.1
  - entrez-direct=22.4
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - krb5=1.21.3
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libcurl=8.10.1
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libidn2=2.3.7
  - libnghttp2=1.64.0
  - libsqlite=3.47.0
  - libssh2=1.11.0
  - zlib=1.3.1