site_name: Pacini-typing
nav:
  - index.md
  - Installation: installation.md
site_author: Mark van de Streek
site_description: Genetic variant typing based on configuration patterns

# site_url: https://to.be.determined...
repo_url: https://github.com/RIVM-bioinformatics/Pacini-typing
dev_addr: 0.0.0.0:8000

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

theme:
  name: material
  navigation_mode: tabs
  features:
    - content.code.copy
    - content.code.annotate 
    - content.code.select
    - navigation.tabs
    - navigation.expand
    - navigation.top

  font:
    text: Roboto Mono
  palette:
    # Dark 
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Dark mode
      primary: ca005d
      accent: deep purple
    # Light
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Light mode
      primary: teal
      accent: teal