site_name: Pacini-typing
nav:
  - Home: index.md
  - Prerequisites: prerequisites.md
  - Installation: installation.md
  - Parameters: parameters.md
  - Usage: usage.md
  - Example Run: example_run.md
site_author: Mark van de Streek
site_description: Genetic variant typing based on configuration patterns

# site_url: https://to.be.determined...
# repo_url: https://github.com/RIVM-bioinformatics/Pacini_typing
repo_url: https://github.com/MarkStreek/MarkStreek
dev_addr: 0.0.0.0:8000

theme:
  name: material
  navigation_mode: tabs
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.expand
    - navigation.top

  font:
    text: Roboto Mono
  palette:
    # Dark 
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Dark mode
      primary: ca005d
      accent: deep purple
    # Light
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Light mode
      primary: teal
      accent: teal