%YAML 1.2
---
metadata:
  filename: "O139.yaml"
  id: "VIB-O139"
  type: "V. cholerae O139 Genes"
  description: "Genetic pattern run config file for Vibrio cholerae O139 serogroup"
  date_created: "2024-11-06"

database:
  name: "VIB-O139"
  path: "databases/VIB-O139"
  target_genes_file: "config/VIB-O139.fasta"

global_settings:
  run_output: "output/"
  perc_ident: 99.8
  perc_cov: 100.0

pattern:
  - gene: "wbfZ"
  - gene: "ctxA"
  - gene: "ctxB"