name: Run Pylint and update README

on:
  push:
    branches:
      - main

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Run Pylint
      id: pylint
      run: |
        pylint_score=$(pylint **/*.py | tee pylint_output.txt | tail -2 | head -1 | grep -oP '\d+(\.\d+)?(?=/10)')
        echo "$pylint_score" >> $GITHUB_ENV
        echo "$pylint_score"

    - name: Update README with Pylint score
      run: |
        sed -i 's/Pylint score: .*/Pylint score: '"$pylint_score"'/g' README.md

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m "Update Pylint score in README"
        git push
